extends:
  - k8s/.lefthook.yml
  - libs/myutil/.lefthook.yml
  - apps/web/.lefthook.yml
  - apps/desktop/.lefthook.yml

pre-commit:
  parallel: true
  commands:
    root-lint:
      run: npx biome check --apply {staged_files}
      stage_fixed: true

commit-msg:
  commands:
    commitlint:
      run: npx --no -- commitlint --edit $1
