extends:
  - k8s/.lefthook.yml
  - apps/web/.lefthook.yml

pre-commit:
  parallel: true
  commands:
    root-eslint:
      run: npx eslint --cache --fix {staged_files}
      stage_fixed: true

commit-msg:
  commands:
    commitlint:
      run: npx --no -- commitlint --edit $1
